---
sudo: true
services:
  - docker
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
script: 'bundle exec rake $CHECK'
env:
  - CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 3.8.0'
  - CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 3.8.0' FUTURE_PARSER=yes
  - CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 4.2.0'
  - CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 4.0'
matrix:
  exclude:
    - rvm: 2.2
      env: CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 3.8.0'
    - rvm: 2.2
      env: CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 3.8.0' FUTURE_PARSER=yes
    - rvm: 2.3
      env: CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 3.8.0'
    - rvm: 2.3
      env: CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 3.8.0' FUTURE_PARSER=yes
  include:
    - rvm: 1.8.7
      dist: precise
      env: CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 3.8.0'
    - rvm: 1.8.7
      dist: precise
      env: CHECK=test STRICT_VARIABLES=yes PUPPET_GEM_VERSION='~> 3.8.0' FUTURE_PARSER=yes
    - rvm: 2.2
      env: CHECK=rubocop
  allow_failures:
    - rvm: 2.3
